name: "Nag's Knights Chess League Test Server"
services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: magnus
      POSTGRES_PASSWORD: bong-cloud
      POSTGRES_DB: chess-league
    networks:
      - net
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "user=magnus password=bong-cloud dbname=chess-league host=database port=5432 sslmode=disable"
      MAGIC_NUMBER: "test123"
    networks:
      - net
    develop:
      watch:
        - action: rebuild
          path: .
networks:
  net:
    name: "Nag's Knights Network"
    driver: bridge
